### PR TITLE
Updated board2016

### PR DESCRIPTION
**Pull request by Kazilico**
I've changed the board members to the current members as well as changed from where their photos are sourced.

### CODE REVIEW

**Comment by jackiekazil** [comment]
Will notify when this is ready.

**Comment by ajb** [comment]
@jackiekazil: the tests are failing because `Gemfile.lock` is not checked-in to `.git`, and Travis is pulling a newer version of the `html-proofer` gem that has some incompatibilities.

If the tests pass locally, I would recommend checking-in your `Gemfile.lock` to version control (by removing it from `.gitignore`.)

**Comment by jackiekazil** [comment]
@ajb and if it is not successfully passing locally?

**Comment by ajb** [comment]
The failure is because of changes in the html-proofer module:
https://github.com/gjtorikian/html-proofer/releases/tag/v3.0.0

You can lock the version to '~>2.0' in your Gemfile, which might help... or
update the code that references it to reflect any changes that happened
between versions 2 and 3.

On Wed, Mar 30, 2016 at 10:53 PM, Jackie Kazil <notifications@github.com>
wrote:

> @ajb <https://github.com/ajb> and if it is not successfully passing
> locally?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/presidential-innovation-foundation/presidential-innovation-foundation.github.io/pull/50#issuecomment-203726663>
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by ajb** [comment]
Hey Jackie, looks like you may have gotten this working. 

I've also added #51, which I would recommend merging regardless.

**Comment by jackiekazil** [comment]
@ajb for looking this over and helping!!!

**Comment by ajb** [comment]
No prob!

On Wed, Mar 30, 2016 at 11:06 PM, Jackie Kazil <notifications@github.com>
wrote:

> @ajb <https://github.com/ajb> for looking this over and helping!!!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/presidential-innovation-foundation/presidential-innovation-foundation.github.io/pull/50#issuecomment-203728992>
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by greggersh** [comment]
I thought @ajb was a Laravel guy.

**Pull request merged**
