### PR TITLE
Blog

### LINKED ISSUE #30: Create a blog / news / announcement feed

### PR DESCRIPTION
**Pull request by benbalter**
Fixes #30

### CODE REVIEW

**Comment by parkr** [comment]
Throw `updates.html` into `updates/index.html` and remove the `permalink` directive in the YAML front matter and the pagination will fix itself.

/cc https://github.com/jekyll/jekyll-paginate/issues/25

**Comment by benbalter** [comment]
:100:% right as always. Thanks @parkr!

**Comment by benbalter** [comment]
`/index.html` footer:

screen shot 2015-03-05 at 4 03 53 pm

`/updates`:

screen shot 2015-03-05 at 4 03 44 pm

An individual post:

screen shot 2015-03-05 at 4 03 49 pm

**Comment by benbalter** [comment]
With feedback, this should be ready to go. Posts are simply added to the `_posts` folder as markdown files, and appear at `/updates/`.

**Pull request merged**
